name: Create Photographic
favicon: null
layout_spectrum: 1
typography_spectrum: 0.59819
title: Create Photographic Commercial Photography
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#a3001c'
    - '#424242'
    - '#e0ddc5'
    - '#a1a2a8'
    - '#7d7c73'
  brandStrength: 0.6875
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
