name: Create Photographic
favicon: null
layout_spectrum: 1
typography_spectrum: 0.15057961829006672
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#a3001c'
    - '#424242'
    - '#e0ddc5'
    - '#a1a2a8'
    - '#7d7c73'
  brandStrength: 0.6875
  lightness: 0.475923974532634
  saturation: 0.41504887235350907
  rhythmicContrast: 0.8218199845869094
purpose: []
