name: Create Photographic
favicon: null
layout_spectrum: 0.861867623636499
typography_spectrum: 0.15057961829006672
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.6982345420401543
  lightness: 0.475923974532634
  saturation: 0.41504887235350907
  rhythmicContrast: 0.8218199845869094
purpose: []
